---
spec/spec_helper_acceptance.rb:
  modules:
    - name: maestrodev-maven
      version: 1.0.0
    - name: puppetlabs-java
      version: 1.0.1
spec/spec_helper.rb:
  default_facts:
    http_proxy:
    maven_version: '3.0.5'
.travis.yml:
  forge_password: "Otm0EXhVvdcqG80+M7bQy6gy+xv/x2hJuQm1PyscRAX7zSnHNDgv85DniqGPxnJlLKxjrWwLwzDQ1+UO5WpaBn0/Oiv2U+M8VrmKq9/YkO3XgL93HZNmKKpJnj+SBR6ZaCml00AbwfTLOOBkUBMHwLDlpkClSvB79rYmKJxkDh0="
